CREATE TABLE IF NOT EXISTS mandals (id VARCHAR(50) PRIMARY KEY, name VARCHAR(255));
CREATE TABLE IF NOT EXISTS panchayats (id VARCHAR(50) PRIMARY KEY, mandal_id VARCHAR(50), name VARCHAR(255));
CREATE TABLE IF NOT EXISTS villages (id VARCHAR(50) PRIMARY KEY, panchayat_id VARCHAR(50), name VARCHAR(255));
TRUNCATE TABLE mandals;
TRUNCATE TABLE panchayats;
TRUNCATE TABLE villages;

INSERT INTO mandals (id, name) VALUES ('M1', 'Ramakuppam');
INSERT INTO mandals (id, name) VALUES ('M2', 'Santhipuram');
INSERT INTO mandals (id, name) VALUES ('M3', 'Gudupalle');
INSERT INTO mandals (id, name) VALUES ('M4', 'Kuppam');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P1', 'M1', '89-PEDDURU');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P10', 'M1', 'KENCHANABALLA');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P100', 'M4', 'VENDUGAMPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P11', 'M1', 'KONGANAPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P12', 'M1', 'MANEEMDRAM');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P13', 'M1', 'MUDDANAPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P14', 'M1', 'NANIYALATHANDA');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P15', 'M1', 'NARAYANAPURAMTHANDA');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P16', 'M1', 'PANDYALAMADUGU');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P17', 'M1', 'PMK THANDA');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P18', 'M1', 'PEDDA THANDA');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P19', 'M1', 'RAJUPETA');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P2', 'M1', 'UNISIGANIPALLI');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P20', 'M1', 'RAMAKUPPAM');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P21', 'M1', 'SINGASAMUDRAM');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P22', 'M1', 'VEERNAMALA');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P23', 'M1', 'VIJILAPURAM');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P24', 'M2', 'Dandikuppam');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P25', 'M2', '121 Pedduru');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P26', 'M2', 'Nadimpalli');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P27', 'M2', 'Regadadinnepalli');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P28', 'M2', 'Karlagatta');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P29', 'M2', 'C BANDAPALLI');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P3', 'M1', 'BAIPAREDLAPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P30', 'M2', 'Abakaladoddi');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P31', 'M2', 'Morasanapalle');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P32', 'M2', 'Kolamadugu');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P33', 'M2', 'MATTAM');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P34', 'M2', 'Anikera');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P35', 'M2', 'Mulluru Krishna Puram');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P36', 'M2', 'Thummisi');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P37', 'M2', '64Pedduru');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P38', 'M2', 'Gunjarlapalle');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P39', 'M2', 'Sivaramapuram');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P4', 'M1', 'BALLA');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P40', 'M2', 'KADAPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P41', 'M2', '30 Sonneganipalli');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P42', 'M2', 'Rallabudugur');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P43', 'M2', 'Kenamakunapalli');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P44', 'M2', 'Chenguballa');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P45', 'M2', 'Konerukuppam');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P46', 'M2', 'CHINNARIDODDI');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P47', 'M3', 'AGARAM');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P48', 'M3', 'BEGGILAPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P49', 'M3', 'CHEEKATIPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P5', 'M1', 'BANDARLAPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P50', 'M3', 'CHINNAGOLLAPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P51', 'M3', 'DASIMANIPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P52', 'M3', 'GUDUPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P53', 'M3', 'GUNDLASAGARAM');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P54', 'M3', 'KANAMANAPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P55', 'M3', 'K.B.PALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P56', 'M3', 'KODATHANAPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P57', 'M3', 'KUPPIGANIPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P58', 'M3', 'O.N.KOTHUR');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P59', 'M3', 'PEDDABADANIWADA');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P6', 'M1', 'CHELDIGANIPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P60', 'M3', 'POGURUPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P61', 'M3', 'SANGANAPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P62', 'M3', 'SETTIPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P63', 'M3', 'SODIGANIPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P64', 'M3', 'YAMAGANIPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P65', 'M4', 'ADAVIBUDUGUR');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P66', 'M4', 'ANANTHAPURAM');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P67', 'M4', 'ANIMIGANIPALLI');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P68', 'M4', 'B S PALLI');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P69', 'M4', 'CHALAMANGALAM');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P7', 'M1', 'CHIKKAPALLI THANDA');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P70', 'M4', 'CHINNAOBANAPALLI');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P71', 'M4', 'CHOKKANDLAPALLI');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P72', 'M4', 'CHANDAM');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P73', 'M4', 'CHEELEPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P74', 'M4', 'CHEEMANAYANIPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P75', 'M4', 'CHEKKUNATHAM');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P76', 'M4', 'DALAVAIKOTHAPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P77', 'M4', 'DASEGOWNIYUR');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P78', 'M4', 'GARIGACHINNEPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P79', 'M4', 'GONUGUR');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P8', 'M1', 'GORIVIMAKULAPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P80', 'M4', 'GUNDLANAYANIPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P81', 'M4', 'JARUGU');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P82', 'M4', 'KAMATHAMUR');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P83', 'M4', 'KANGUNDI');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P84', 'M4', 'KOTALURU');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P85', 'M4', 'KOTHAPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P86', 'M4', 'KRISHNADASANAPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P87', 'M4', 'KUPPAM (MAJOR PTS)');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P88', 'M4', 'MALLANURU');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P89', 'M4', 'MANKALADODDI');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P9', 'M1', 'GUTTURU THANDA');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P90', 'M4', 'MITTAPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P91', 'M4', 'NADIMUR');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P92', 'M4', 'NOOLAKUNTA');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P93', 'M4', 'PAIPALYAM');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P94', 'M4', 'PEDDA BANGARUNATHAM');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P95', 'M4', 'SAMAGUTTAPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P96', 'M4', 'THAMBIGANIPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P97', 'M4', 'URLAOBANAPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P98', 'M4', 'VANAGUTTAPALLE');
INSERT INTO panchayats (id, mandal_id, name) VALUES ('P99', 'M4', 'VASANADU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H1', 'P1', 'Pedduru');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H10', 'P2', 'Maruvuru');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H100', 'P18', 'Pedda Thanda');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H101', 'P18', 'Thulasinaick Thanda');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H102', 'P18', 'Bandakothuru Thanda');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H103', 'P18', 'Inderacolony');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H104', 'P18', 'Addugattu Thanda');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H105', 'P19', 'Rajupeta');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H106', 'P20', 'Ramakuppam');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H107', 'P20', 'Akandaganipalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H108', 'P20', 'Chennaredlapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H109', 'P20', 'Mittapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H11', 'P2', 'Jampuru');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H110', 'P20', 'Thimmasamudram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H111', 'P20', 'Kempasamudram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H112', 'P20', 'Kotlaguru');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H113', 'P20', 'Harijanakota');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H114', 'P20', 'Venkatapuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H115', 'P20', 'Ayyappaganipalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H116', 'P21', 'Singasamudram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H117', 'P21', 'Jeedimakula Palli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H118', 'P21', 'Kuppigani Palli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H119', 'P21', 'Reddyvaripalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H12', 'P3', 'Baiparedlapalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H120', 'P21', 'Chintamanatham');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H121', 'P22', 'Veernamala');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H122', 'P22', 'Neelichenu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H123', 'P22', 'Podichenu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H124', 'P22', 'Uribayataindllu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H125', 'P22', 'Nallarallachenu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H126', 'P22', 'Gurukulamadugu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H127', 'P22', 'Sanyasiganivanka');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H128', 'P22', 'Vemanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H129', 'P22', 'Kullaganuru');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H13', 'P3', 'Jogindlu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H130', 'P23', 'Vijalapuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H131', 'P23', 'Ankireddipalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H132', 'P23', 'Balaobanapalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H133', 'P23', 'Battuvaripalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H134', 'P23', 'Bokkalam Gadda');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H135', 'P23', 'Kadisanakuppam');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H136', 'P23', 'Kilakipodu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H137', 'P24', 'Dandikuppam');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H138', 'P24', 'Nallarallapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H139', 'P24', 'Chowdampalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H14', 'P3', 'Vardhikuppam');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H140', 'P24', 'Siddaredlapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H141', 'P24', 'Kondapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H142', 'P24', 'Nimmanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H143', 'P24', 'Indiranagar');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H144', 'P24', 'Krishnepalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H145', 'P25', 'pedduru');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H146', 'P25', 'J B Kotturu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H147', 'P25', 'bendanakuppam');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H148', 'P26', 'Nadimpalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H149', 'P26', 'rangepalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H15', 'P4', 'Balla');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H150', 'P27', 'Regadadinnepalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H151', 'P27', 'Nallapareddiyuru');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H152', 'P27', 'Chinnagandlapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H153', 'P28', 'Karlagatta');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H154', 'P28', 'ChinnaKarlagatta');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H155', 'P28', 'Thamiganipalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H156', 'P28', 'Venkatapuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H157', 'P28', 'Cheemanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H158', 'P28', 'Preethichamunuru');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H159', 'P29', 'C bandapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H16', 'P4', 'Agraharam Dinne');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H160', 'P29', 'chinnuru');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H161', 'P29', 'chigrlapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H162', 'P29', 'bevanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H163', 'P29', 'rallapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H164', 'P29', 'Muddanapalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H165', 'P29', 'dt palli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H166', 'P30', 'Abakaladoddi');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H167', 'P30', 'Jangalapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H168', 'P30', 'Kothigutlapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H169', 'P30', 'Veduruguttapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H17', 'P4', 'Peddakurabalapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H170', 'P30', 'kakarlavanka');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H171', 'P30', 'Adduvanka');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H172', 'P30', 'Venkateshpuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H173', 'P30', 'Gangapuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H174', 'P30', 'Abakaladoddi colony');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H175', 'P31', 'morasanapalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H176', 'P31', 'pakkampalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H177', 'P31', 'kanamaladoddi');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H178', 'P31', 'Narasimhapalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H179', 'P31', 'jalliganipalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H18', 'P4', 'Lakshminagar');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H180', 'P32', 'Kolamadugu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H181', 'P32', 'V kothuru');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H182', 'P32', 'Ammavaripeta');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H183', 'P32', 'Ramapuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H184', 'P32', 'Voddumadi');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H185', 'P32', 'Kadhirimuthanapalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H186', 'P32', 'Jeedimanipalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H187', 'P32', 'Redlapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H188', 'P32', 'Chillumanipalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H189', 'P33', 'MATTAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H19', 'P4', 'Palarevugadda');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H190', 'P33', 'PONNEYPALLI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H191', 'P33', 'GT PALLI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H192', 'P33', 'Santampalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H193', 'P33', 'KP MITTA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H194', 'P33', 'SANTHURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H195', 'P33', 'Venkateshpuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H196', 'P33', 'CHITTEPALLI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H197', 'P33', 'Gollapalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H198', 'P34', 'Anikera');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H199', 'P34', 'jogindlu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H2', 'P1', 'Naniyala');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H20', 'P4', 'Singampalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H200', 'P34', 'Bellakogila');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H201', 'P34', 'Vadagandlapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H202', 'P34', 'B kotturu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H203', 'P34', 'Settepalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H204', 'P35', 'Mulluru');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H205', 'P35', 'Krishna Puram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H206', 'P36', 'Thummisi');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H207', 'P36', 'Donkumanipalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H208', 'P36', 'Thulasinayanapalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H209', 'P36', 'Buradasidanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H21', 'P4', 'Krishnapuram Dinne');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H210', 'P37', '64Pedduru');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H211', 'P37', 'Somapuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H212', 'P37', 'Gasikapalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H213', 'P37', 'Solisettipalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H214', 'P37', 'Karumutla');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H215', 'P38', 'Gunjarlapalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H216', 'P38', 'Nakkanapalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H217', 'P38', 'Peddabommanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H218', 'P38', 'Kareganuru');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H219', 'P38', 'T Kothuru');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H22', 'P4', 'Viplavaram Gadda');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H220', 'P38', 'Chinthakampalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H221', 'P39', 'Sivaramappuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H222', 'P39', 'Gatturu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H223', 'P39', 'Nanjam Peta');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H224', 'P39', 'Kotha Indlu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H225', 'P39', 'Kota Gadda');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H226', 'P39', 'Odduvanka');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H227', 'P39', 'Anchinayani Kuppam');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H228', 'P39', 'Santhampalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H229', 'P40', 'KADAPALLI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H23', 'P4', 'Kothapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H230', 'P40', 'SHYAMARAJAPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H231', 'P40', 'PODURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H232', 'P40', 'KALIGANURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H233', 'P40', 'KADIRIOBANA PALLI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H234', 'P40', 'MADANAPALLI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H235', 'P40', 'B M GOLLAPALLI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H236', 'P40', 'BEERANAKUPPAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H237', 'P40', 'TIMMARAJUPALLI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H238', 'P40', 'SILAMAKULA RAI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H239', 'P40', 'PODUCHENULU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H24', 'P4', 'Nadipichinne Palli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H240', 'P40', 'CHALIMIVANKA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H241', 'P41', 'Sonneganipalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H242', 'P41', 'Kutheganipalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H243', 'P41', 'Nayanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H244', 'P41', 'Gundasettipalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H245', 'P42', 'Rallabudugur');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H246', 'P42', 'settigani kuraburu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H247', 'P42', 'Gollapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H248', 'P42', 'Rameganipalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H249', 'P42', 'Banda thippanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H25', 'P5', 'Bandarlapalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H250', 'P42', 'shesadripuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H251', 'P42', 'pilliganipalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H252', 'P42', 'sathu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H253', 'P42', 'Reddivaripalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H254', 'P43', 'kenamakunapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H255', 'P43', 'gadduru');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H256', 'P43', 'arimuthanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H257', 'P43', 'santhipuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H258', 'P43', 'bodumakunapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H259', 'P44', 'chenguballa');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H26', 'P5', 'Bagalanatham');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H260', 'P44', 'SETTIBALLA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H261', 'P44', 'SOGADABALLA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H262', 'P44', 'SIVAKURUBURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H263', 'P44', 'VADDIVANI KOTTHURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H264', 'P45', 'konerukuppam');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H265', 'P45', 'kolalathinmanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H266', 'P46', 'CHINNARIDODDI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H267', 'P46', 'KOTHA PETA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H268', 'P46', 'K T PALLI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H269', 'P46', 'S GOLLAPALLI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H27', 'P5', 'Gernipalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H270', 'P47', 'AGARAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H271', 'P47', 'JABBIGANIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H272', 'P47', 'KOTHAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H273', 'P47', 'JOGINDLU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H274', 'P47', 'THODELUGATTU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H275', 'P48', 'NALAGAMPALLE (PES)');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H276', 'P48', 'GOKARLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H277', 'P48', 'BEGGILAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H278', 'P48', 'BANDAKOTHURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H279', 'P49', 'CHEEKATIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H28', 'P5', 'Saginekuppam');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H280', 'P49', 'KOTAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H281', 'P49', 'PACHARLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H282', 'P49', 'VENKAPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H283', 'P50', 'KODIGANIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H284', 'P50', 'MALAVANIKOTHURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H285', 'P50', 'PEDDAGOLLAPLLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H286', 'P50', 'CHINNAGOLLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H287', 'P50', 'JOGINDLU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H288', 'P50', 'AYYAVARIGOLLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H289', 'P51', 'DASIMANIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H29', 'P5', 'Peruru');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H290', 'P51', 'ATHINATHAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H291', 'P51', 'BISANATHAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H292', 'P51', 'AVULACHERUVU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H293', 'P51', 'MUTHYALAPALEM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H294', 'P52', 'GUDUPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H295', 'P52', 'IRISIGANIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H296', 'P52', 'BIJJIGANIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H297', 'P52', 'VENGEPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H298', 'P52', 'GUDUPALLE H.W');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H299', 'P52', 'KADEPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H3', 'P1', 'Arimanipenta');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H30', 'P5', 'Errachenulu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H300', 'P52', 'MITTORU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H301', 'P53', 'GUNDLASAGARAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H302', 'P53', 'GUTTARLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H303', 'P54', 'KANAMANAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H304', 'P54', 'KANAMANAPALLE H.W');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H305', 'P54', 'MIDDORU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H306', 'P55', 'KANCHIBANDARLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H307', 'P55', 'ELLAPPA KOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H308', 'P55', '114 SETTIPALLE@CHINNABA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H309', 'P56', 'AVULATHIMMANAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H31', 'P5', 'Errachenulu St Colony');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H310', 'P56', 'SALACHINTHANAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H311', 'P56', 'GUDICHEMBAGIRI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H312', 'P56', 'KODATHANAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H313', 'P57', 'ONTIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H314', 'P57', 'KOTACHEMBAGIRI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H315', 'P57', 'KUPPIGANIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H316', 'P57', 'SIRIGIRIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H317', 'P57', 'ONTIPALLE RAILWAY STATION');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H318', 'P58', 'CHINNAKOTAMAKINAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H319', 'P58', 'THALAI AGRAHARAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H32', 'P5', 'Kotarigadda');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H320', 'P58', 'KOTAMAKINAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H321', 'P58', 'CHINNA AGRAHARAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H322', 'P58', 'KRISHNARAJAPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H323', 'P58', 'KONDASAMUDRAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H324', 'P58', 'SREENIVASAPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H325', 'P58', 'O.N.KOTHURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H326', 'P59', 'GUDIKOTHURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H327', 'P59', 'PEDDABADANIVADA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H328', 'P59', 'KAMMAGUTTAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H329', 'P59', 'JATHIKARTHANAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H33', 'P5', 'Boyanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H330', 'P59', 'VEPAMANIKOTHURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H331', 'P59', 'JOGINDLU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H332', 'P59', 'JANGALAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H333', 'P59', 'PEDDONI KOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H334', 'P59', 'SOLAPPAGARI KOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H335', 'P59', 'SARIGAVARI KOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H336', 'P59', 'AMMAVARIPETA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H337', 'P59', 'PAPANURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H338', 'P60', 'ANGANAMALAKOTHURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H339', 'P60', 'POGURUPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H34', 'P5', 'Jampiredy Cheruvu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H340', 'P60', 'LINGAPURAM DINNE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H341', 'P60', 'CHINTHARAPALEM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H342', 'P60', 'KARAMUTLA GOLLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H343', 'P61', 'BURUGULAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H344', 'P61', 'CHINNAPARTHIKUNTA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H345', 'P61', 'BOYANAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H346', 'P61', 'SANGANAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H347', 'P61', 'PEDDAPARTHIKUNTA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H348', 'P61', 'JOGINDLU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H349', 'P62', 'SETTIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H35', 'P5', 'Ontigopanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H350', 'P62', 'GOVINDAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H351', 'P62', 'KAPPALANATHAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H352', 'P62', 'CHINNASETTIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H353', 'P62', 'JOGGANURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H354', 'P62', 'KRISHNEGOWNI KOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H355', 'P63', 'THOTLIGANIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H356', 'P63', 'ALUGUMANIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H357', 'P63', 'SODIGANI PALEM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H358', 'P63', 'SONNARSANAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H359', 'P63', 'VADDIGOLLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H36', 'P5', 'Giddapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H360', 'P63', 'ANAGARLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H361', 'P63', 'KAKINAYUNICHIGARLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H362', 'P63', 'MALDEPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H363', 'P63', 'SODIGANIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H364', 'P63', 'DIGUVACHIGARLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H365', 'P63', 'BURIDIGANIKUNTA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H366', 'P63', 'THIMMINAYUNIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H367', 'P63', 'MALDEPALLE KOTHURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H368', 'P63', 'DINNEPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H369', 'P64', 'YAMAGANIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H37', 'P5', 'Pamanaboyanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H370', 'P64', 'ADAVIBADANIWADA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H371', 'P65', 'Adavibudugur');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H372', 'P65', 'Eguvabudugur');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H373', 'P65', 'Vasanadu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H374', 'P65', 'V Kothur');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H375', 'P66', 'Ananthapuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H376', 'P66', 'Bandarlapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H377', 'P66', 'K Kothur');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H378', 'P66', 'Nayanoripalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H379', 'P67', 'Animiganipalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H38', 'P5', 'Birugundlapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H380', 'P67', 'Boovanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H381', 'P68', 'B S Palli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H382', 'P68', 'K G Vada');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H383', 'P69', 'Chalamangalam');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H384', 'P69', 'Pathapeta');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H385', 'P69', 'Gownivari Palli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H386', 'P69', 'Diguvapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H387', 'P69', 'Sanganapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H388', 'P69', 'Reddivaripalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H389', 'P69', 'Krishnadhasanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H39', 'P5', 'Tagalathanda');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H390', 'P70', 'Chinnaobanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H391', 'P70', 'Nayanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H392', 'P70', 'Peddaobanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H393', 'P71', 'Chokkandlapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H394', 'P65', 'ADAVIBUDUGURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H395', 'P65', 'ADAVIBUDUGUR H.W');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H396', 'P65', 'VINAYAKAPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H397', 'P65', 'MOTURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H398', 'P65', 'YERRAGUTTA CHENU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H399', 'P65', 'VINAYAKAPURAM S.C.COLON');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H4', 'P2', 'Unisiganipalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H40', 'P5', 'Nakkabalepalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H400', 'P67', 'ANIMIGANIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H401', 'P67', 'JAMBUCHERUVU KOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H402', 'P72', 'EKARLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H403', 'P72', 'CHANDAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H404', 'P72', 'CHANDM H.W');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H405', 'P72', 'KOTHAINDLU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H406', 'P72', 'ABBUKUNTA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H407', 'P73', 'PALARLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H408', 'P73', 'BEVANAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H409', 'P73', 'PARAMASAMUDRAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H41', 'P5', 'Vinayakapuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H410', 'P73', 'VADDIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H411', 'P73', 'PARAMASAMUDRAM H.W');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H412', 'P73', 'CHEELEPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H413', 'P73', 'VADDIINDULU @ PYURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H414', 'P74', 'CHEEMANAYANIPALLE @ LAK');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H415', 'P74', 'LAKSHMIPURAM COLONY');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H416', 'P74', 'VINAYAKAPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H417', 'P74', 'GERISABAVI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H418', 'P74', 'KOTAMURU @ BABU NAGAR');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H419', 'P74', 'SURAPPAKOTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H42', 'P5', 'Govindarajapuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H420', 'P74', 'BAIRUGANIPALLE KOTAL');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H421', 'P74', 'VINAYAKAPURAM (ANADICOL');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H422', 'P75', 'PEDDABOGGUPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H423', 'P75', 'CHEKKUNATHAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H424', 'P75', 'KANAMAPACHARLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H425', 'P75', 'ADAVIMULAKALAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H426', 'P75', 'S.C.COLONY NORTH');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H427', 'P75', 'KUSURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H428', 'P75', 'THUMMALAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H429', 'P75', 'PAICHEKKUNATHAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H43', 'P5', 'Eddulaagattu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H430', 'P75', 'KALANURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H431', 'P75', 'BALAPPAKOTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H432', 'P75', 'S.C.COLONY SOUTH');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H433', 'P75', 'DOLLAGUTTA (S.T.COLONY)');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H434', 'P75', 'MADDULAVANKA KOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H435', 'P75', 'ZATARIMADUGU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H436', 'P75', 'BABUNAGARCOLONY');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H437', 'P75', 'KOTHURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H438', 'P75', 'GOWDAPPANURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H439', 'P75', 'ATHURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H44', 'P5', 'Krishnamanayanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H440', 'P75', 'KULLAYAPPAKOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H441', 'P75', 'UPPUKUNTA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H442', 'P76', 'CHINNAKURABALAPALLE (RU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H443', 'P76', 'DALAVOIKOTHAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H444', 'P76', 'HARIJANA WADA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H445', 'P76', 'SRI LANKA REPARTRITES C');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H446', 'P76', 'N.T.R.COLONY');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H447', 'P76', 'URBANCOLONY');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H448', 'P76', 'MODERN COLONY');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H449', 'P77', 'DASEGOWNIYURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H45', 'P5', 'Krishnanagar Colony');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H450', 'P77', 'BOGGUPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H451', 'P77', 'GUTTAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H452', 'P77', 'BAYYANURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H453', 'P77', 'VAGARAPPAKOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H454', 'P77', 'GUTTAPALLE COLONY');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H455', 'P77', 'BALAMANDAKOTTAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H456', 'P77', 'BAIRAPPAKOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H457', 'P77', 'EGILERAPPAKOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H458', 'P77', 'RAMNAGAR');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H459', 'P77', 'NARAYANAPURAM(PART)');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H46', 'P5', 'Nernelli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H460', 'P78', 'KAKIMADUGU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H461', 'P78', 'EGUVAKAKIMADUGU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H462', 'P78', 'GARIGACHINNEPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H463', 'P78', 'DIGUVAKAKIMADUGU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H464', 'P78', 'GARIGACHINNEPALLE S.C.C');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H465', 'P78', 'DOMMARAAGRAHARAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H466', 'P79', 'GONUGURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H467', 'P79', 'GUTTAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H468', 'P80', 'URINAYANIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H469', 'P80', 'URINAYANIKOTHURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H47', 'P5', 'Lingapuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H470', 'P80', 'GUDLANAYAANIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H471', 'P81', 'PORAKUNTLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H472', 'P81', 'JARUGU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H473', 'P81', 'BATHALAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H474', 'P81', 'CHALARLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H475', 'P81', 'JOGINDLU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H476', 'P81', 'YANAMANASANAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H477', 'P82', 'KAMATHAMURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H478', 'P82', 'KATHIMANIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H479', 'P82', 'DOMMARAINDLU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H48', 'P5', 'Kanchidasanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H480', 'P82', 'KATHIMANIPALLE COLONY');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H481', 'P82', 'GUNDLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H482', 'P82', 'GULLEPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H483', 'P83', 'VENKATESHPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H484', 'P83', 'KANGUNDI R.F');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H485', 'P83', 'KANGUNDI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H486', 'P83', 'PEDDAVANKA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H487', 'P83', 'NAYANURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H488', 'P83', 'MANGAMMAVURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H489', 'P83', 'BRAMHADEVARACHENULU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H49', 'P5', 'Kodigundlapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H490', 'P83', 'OTIKUNTA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H491', 'P83', 'THAGARAMANIMOOLA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H492', 'P83', 'KOWSIGANDLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H493', 'P83', 'PARVATHIPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H494', 'P83', 'GIDDEGANIPANETA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H495', 'P83', 'GANESHPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H496', 'P83', 'KRISHNAPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H497', 'P83', 'NAKKALA GUTTA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H498', 'P83', 'SAMADULU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H499', 'P83', 'DEVARAJAPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H5', 'P2', 'Aniganuru');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H50', 'P5', 'Lakshmipuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H500', 'P83', 'SAHIPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H501', 'P83', 'VENKATRAJAPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H502', 'P83', 'AMBAPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H503', 'P83', 'THIRLAVANIBANDA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H504', 'P83', 'RAMALAGUTTA CHENU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H505', 'P83', 'S.C.COLONY');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H506', 'P83', 'KADIRIPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H507', 'P83', 'S.T.COLONY');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H508', 'P83', 'NARAYANAPURAM (T.N.BORD');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H509', 'P84', 'KOTALURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H51', 'P5', 'Gadduru');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H510', 'P84', 'YANADIPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H511', 'P84', 'RALLACHENU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H512', 'P84', 'SIDDAPPANURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H513', 'P84', 'MESTRINAYANURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H514', 'P84', 'YERRAMANNUGUNTHALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H515', 'P84', 'NURAVULAGUNDLACHENU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H516', 'P84', 'GUNDLAMADUGU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H517', 'P84', 'SAMIDAMMA VANKA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H518', 'P84', 'SAPPANIKUNTA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H519', 'P84', 'BALAMKOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H52', 'P5', 'Yanadi Colony');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H520', 'P84', 'VEPPALACHENU SC COLONY');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H521', 'P85', 'KOTHAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H522', 'P85', 'NIMMAKAMPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H523', 'P85', 'SAJJALAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H524', 'P85', 'KADIRIPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H525', 'P86', 'VARAMANURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H526', 'P86', 'KRISHNADASANAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H527', 'P86', 'YANADIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H528', 'P86', 'RAJANAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H529', 'P86', 'CHIMPANAGALLU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H53', 'P24', 'Dandikuppam');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H530', 'P86', 'MATARLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H531', 'P86', 'GANGAPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H532', 'P86', 'PAPANNA KUNTA INDLU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H533', 'P87', 'BAIRUGANIPALLE (RURAL)');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H534', 'P87', 'KUPPAM(U)');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H535', 'P88', 'MOTTAKADIRINURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H536', 'P88', 'PONNANGURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H537', 'P88', 'CHINNAOBBA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H538', 'P88', 'T.SADUMURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H539', 'P88', 'PARTHICHENU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H54', 'P24', 'Nallarallapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H540', 'P88', 'HANUMANNAKOTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H541', 'P88', 'MOTLACHENU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H542', 'P88', 'MALLANURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H543', 'P88', 'KRISHNAPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H544', 'P88', 'SINGARAPURAM KOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H545', 'P88', 'VALURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H546', 'P88', 'KODIGANURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H547', 'P88', 'PAIBODAGUTTA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H548', 'P88', 'PEDDANNAKOTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H549', 'P88', 'PONNAGURU COLONY');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H55', 'P24', 'Chowdampalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H550', 'P88', 'JEEDURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H551', 'P88', 'KOTHACHENU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H552', 'P88', 'DIGUVABODAGUTTA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H553', 'P88', 'BODEPPAKOTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H554', 'P88', 'MUTHURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H555', 'P88', 'MUDDULACHERUVU COLONY');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H556', 'P88', 'BIKKILIGATTU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H557', 'P89', 'PEDDAGOPANAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H558', 'P89', 'MULAKALAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H559', 'P89', 'CHINNAGOPANAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H56', 'P24', 'Siddaredlapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H560', 'P89', 'THELLACHERUVU KOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H561', 'P89', 'DIGUVAMANKALADODDI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H562', 'P89', 'SETTIGANIGUTTA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H563', 'P89', 'EGUVAMANKALADODDI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H564', 'P89', 'KONAIAH KUNTA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H565', 'P90', 'MITTAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H566', 'P90', 'AVULANATHAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H567', 'P90', 'VEPURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H568', 'P90', 'THIMMAPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H569', 'P90', 'ADAMANDLA KUPPAM (MITTA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H57', 'P24', 'Kondapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H570', 'P90', 'AVULANATHAM GATE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H571', 'P90', 'VEPANAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H572', 'P91', 'NADIMURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H573', 'P91', 'GUDLAKADIREPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H574', 'P91', 'VASANADUGOLLAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H575', 'P91', 'BODAGUTTAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H576', 'P91', 'RAMABADRANURU (PART) II');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H577', 'P91', 'BAPANACHERUVU @ HAMSAPU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H578', 'P91', 'BIRADANAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H579', 'P91', 'VEERANAGAPURAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H58', 'P24', 'Nimmanapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H580', 'P91', 'JOGINDLU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H581', 'P91', 'PAINASI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H582', 'P91', 'RAMABADRANURU (PART) I');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H583', 'P91', 'VENKATESWARA KOTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H584', 'P91', 'THOTLAMMA GUDI');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H585', 'P92', 'NOOLAKUNTA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H586', 'P92', 'KUTTIGANIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H587', 'P92', 'DAYYALAVANKA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H588', 'P93', 'PAIPALEM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H589', 'P93', 'CHINNABOGGUPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H59', 'P24', 'Indiranagar');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H590', 'P93', 'THANGEDUKUPPAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H591', 'P93', 'PEDDONIKOTALU@VINAYAKAP');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H592', 'P93', 'PAIPALEM B.C.COLONY');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H593', 'P94', 'KUNJEGOWNIYURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H594', 'P94', 'PEDDABANGARUNATHAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H595', 'P94', 'CHINNABANGARUNATHAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H596', 'P94', 'ERRABETAYYANURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H597', 'P94', 'CHALARLAPALLE MITTA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H598', 'P94', 'MARWADA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H599', 'P94', 'P.B.NATHAM B.C.COLONY');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H6', 'P2', 'Govindapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H60', 'P24', 'Krishnepalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H600', 'P95', 'BANDASETTIPALE (RURAL)');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H601', 'P95', 'ELAJANURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H602', 'P95', 'SAMAGUTTAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H603', 'P95', 'SEEGALAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H604', 'P95', 'THANJAMMAKOTTAM @ CHAPP');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H605', 'P95', 'CHINNA SEEGALPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H606', 'P95', 'PEDDANNAKOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H607', 'P95', 'JALLAPPAKOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H608', 'P95', 'NARAYANAPURAM(PART)');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H609', 'P96', 'THAMBIGANIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H61', 'P47', 'AGARAM');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H610', 'P96', 'THAMBIGANIPALLE KOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H611', 'P96', 'THAMBIGANIPALLE ELE.SUB');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H612', 'P96', 'THAMBIGANIPALLE S.C.COL');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H613', 'P97', 'MARAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H614', 'P97', 'KURMANIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H615', 'P97', 'URLAOBANAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H616', 'P97', 'GATTAPANAYANIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H617', 'P97', 'MALLAMMA CHERUVU KOTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H618', 'P97', 'PAPAIAHCHERUVU KOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H619', 'P97', 'MALLIKUNTA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H62', 'P47', 'JABBIGANIPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H620', 'P97', 'ADEPPAKOTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H621', 'P97', 'ANANDAPPA KOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H622', 'P98', 'RAGIMANUMITTA');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H623', 'P98', 'JAMPANURU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H624', 'P98', 'VANAGUTTAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H625', 'P98', 'VANAGUTTAPALLE SC COLONY');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H626', 'P99', 'VASANADU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H627', 'P99', 'CHINNA VASANADU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H628', 'P100', 'VENDUGAMPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H629', 'P100', 'BAIRAPPA KOTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H63', 'P47', 'KOTHAPALLE');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H630', 'P100', 'MALLANURU KOTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H631', 'P100', 'DHARMARAJU KOTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H632', 'P100', 'THANDAVAPPA KOTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H633', 'P100', 'JAMBUCHERUVU KOTTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H634', 'P100', 'BUJANGAPPAKOTALU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H635', 'P100', 'VENDUGAMPALLE B.C.COLON');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H64', 'P47', 'JOGINDLU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H65', 'P47', 'THODELUGATTU');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H66', 'P8', 'Chinnabaldar');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H67', 'P9', 'Gutturu Thanda');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H68', 'P9', 'Uyyalamarrimanu Thanda');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H69', 'P10', 'Kenchanaballa');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H7', 'P2', 'Peddaganuru');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H70', 'P10', 'Bhumandalapuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H71', 'P10', 'Veeranagapuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H72', 'P10', 'Gandhinagar');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H73', 'P10', 'Jambukunta');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H74', 'P10', 'Reddivanipodu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H75', 'P10', 'Kotachenu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H76', 'P10', 'Pacharumakulapalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H77', 'P11', 'Konganapalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H78', 'P11', 'Kollupalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H79', 'P11', 'Venkatapuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H8', 'P2', 'Goolipalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H80', 'P12', 'Manendram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H81', 'P12', 'Attikuppam');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H82', 'P12', 'Chintakuppam');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H83', 'P12', 'Krishnarajapuram');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H84', 'P12', 'Moddulavanka');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H85', 'P12', 'Vankachenu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H86', 'P12', 'Kambaladevanapalle');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H87', 'P13', 'Muddanapalle.');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H88', 'P13', 'Avulakuppam');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H89', 'P14', 'Naniyala Thanda');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H9', 'P2', 'Jowkupalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H90', 'P14', 'Ramapuram Thanda');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H91', 'P15', 'Narayanapuram Thanda');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H92', 'P16', 'Kavampalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H93', 'P16', 'Pallikuppam');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H94', 'P16', 'Pandyalamadugu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H95', 'P16', 'S Gollapalli');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H96', 'P16', 'Kavalimadugu');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H97', 'P16', 'Motlavanka');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H98', 'P17', 'Pmk Thanda');
INSERT INTO villages (id, panchayat_id, name) VALUES ('H99', 'P17', 'Pm Thanda');